# Use case configuration for Xiaomi Pad 6S Pro (sheng)
# Author: map220v <map220v300@gmail.com>

Syntax 4

SectionUseCase."HiFi" {
	File "/Xiaomi/sheng/HiFi.conf"
	Comment "HiFi quality Music."
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
